/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\tempFile\\newblog\\tangblog\\docx\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-257d2156",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-257d2156").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-116da82a",
    path: "/blogs/backEnd/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-116da82a").then(next)
    },
  },
  {
    name: "v-2a04114b",
    path: "/blogs/git/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a04114b").then(next)
    },
  },
  {
    name: "v-3851df6b",
    path: "/blogs/git/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3851df6b").then(next)
    },
  },
  {
    name: "v-1bb6432b",
    path: "/blogs/git/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bb6432b").then(next)
    },
  },
  {
    name: "v-71ff19ea",
    path: "/blogs/css/001.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71ff19ea").then(next)
    },
  },
  {
    name: "v-0838576f",
    path: "/blogs/javascript/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0838576f").then(next)
    },
  },
  {
    name: "v-64840a76",
    path: "/blogs/html/svg%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64840a76").then(next)
    },
  },
  {
    path: "/blogs/html/svg学习.html",
    redirect: "/blogs/html/svg%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/html/svg学习.html",
    redirect: "/blogs/html/svg%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-fa97a9e6",
    path: "/blogs/javascript/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa97a9e6").then(next)
    },
  },
  {
    name: "v-39bcd67e",
    path: "/blogs/javascript/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39bcd67e").then(next)
    },
  },
  {
    name: "v-15b27771",
    path: "/blogs/javascript/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15b27771").then(next)
    },
  },
  {
    name: "v-ecadaec6",
    path: "/blogs/javascript/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ecadaec6").then(next)
    },
  },
  {
    name: "v-44fe92be",
    path: "/blogs/jq/%E6%BB%91%E5%9D%97%E9%AA%8C%E8%AF%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44fe92be").then(next)
    },
  },
  {
    path: "/blogs/jq/滑块验证.html",
    redirect: "/blogs/jq/%E6%BB%91%E5%9D%97%E9%AA%8C%E8%AF%81.html"
  },
  {
    path: "/blogs/jq/滑块验证.html",
    redirect: "/blogs/jq/%E6%BB%91%E5%9D%97%E9%AA%8C%E8%AF%81.html"
  },
  {
    name: "v-ec35f02a",
    path: "/blogs/other/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec35f02a").then(next)
    },
  },
  {
    name: "v-1bcfb7aa",
    path: "/blogs/other/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bcfb7aa").then(next)
    },
  },
  {
    name: "v-21b1ebab",
    path: "/blogs/other/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21b1ebab").then(next)
    },
  },
  {
    name: "v-54690c6a",
    path: "/blogs/other/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54690c6a").then(next)
    },
  },
  {
    name: "v-8d02612a",
    path: "/blogs/other/7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8d02612a").then(next)
    },
  },
  {
    name: "v-6d985d8b",
    path: "/blogs/other/6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d985d8b").then(next)
    },
  },
  {
    name: "v-3dfe960b",
    path: "/blogs/other/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3dfe960b").then(next)
    },
  },
  {
    name: "v-b5a8656a",
    path: "/blogs/perform/001.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5a8656a").then(next)
    },
  },
  {
    name: "v-0418ec4b",
    path: "/blogs/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0418ec4b").then(next)
    },
  },
  {
    name: "v-3f9c92aa",
    path: "/blogs/perform/002.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f9c92aa").then(next)
    },
  },
  {
    name: "v-563d896b",
    path: "/blogs/perform/004.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-563d896b").then(next)
    },
  },
  {
    name: "v-0a19401c",
    path: "/blogs/think/%E5%81%9A%E4%BA%8B%E7%9A%84%E4%B8%89%E4%B8%AA%E5%A2%83%E7%95%8C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a19401c").then(next)
    },
  },
  {
    path: "/blogs/think/做事的三个境界.html",
    redirect: "/blogs/think/%E5%81%9A%E4%BA%8B%E7%9A%84%E4%B8%89%E4%B8%AA%E5%A2%83%E7%95%8C.html"
  },
  {
    path: "/blogs/think/做事的三个境界.html",
    redirect: "/blogs/think/%E5%81%9A%E4%BA%8B%E7%9A%84%E4%B8%89%E4%B8%AA%E5%A2%83%E7%95%8C.html"
  },
  {
    name: "v-e4b2a36a",
    path: "/blogs/vuecode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4b2a36a").then(next)
    },
  },
  {
    name: "v-e8bc8080",
    path: "/blogs/vue/vue%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8bc8080").then(next)
    },
  },
  {
    path: "/blogs/vue/vue函数式组件.html",
    redirect: "/blogs/vue/vue%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/blogs/vue/vue函数式组件.html",
    redirect: "/blogs/vue/vue%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-c3e489ca",
    path: "/blogs/views/messageBoard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c3e489ca").then(next)
    },
  },
  {
    name: "v-cd1e0cea",
    path: "/blogs/vuecode/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd1e0cea").then(next)
    },
  },
  {
    name: "v-1b37a00b",
    path: "/blogs/perform/003.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b37a00b").then(next)
    },
  },
  {
    name: "v-138bd3eb",
    path: "/blogs/vuecode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-138bd3eb").then(next)
    },
  },
  {
    name: "v-1f561f2b",
    path: "/blogs/vuecode/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f561f2b").then(next)
    },
  },
  {
    name: "v-2b206a6b",
    path: "/blogs/vuecode/6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b206a6b").then(next)
    },
  },
  {
    name: "v-9df4dfea",
    path: "/blogs/vuecode/7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9df4dfea").then(next)
    },
  },
  {
    name: "v-b589766a",
    path: "/blogs/vuecode/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b589766a").then(next)
    },
  },
  {
    name: "v-36eab5ab",
    path: "/blogs/vuecode/8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36eab5ab").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-4aea34c9",
    path: "/tag/Python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4aea34c9").then(next)
    },
    meta: {"pid":"tags","id":"Python"}
  },
  {
    path: "/tag/Python/index.html",
    redirect: "/tag/Python/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-3231af64",
    path: "/tag/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3231af64").then(next)
    },
    meta: {"pid":"tags","id":"npm"}
  },
  {
    path: "/tag/npm/index.html",
    redirect: "/tag/npm/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-e8d86dc8",
    path: "/tag/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d86dc8").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/index.html",
    redirect: "/tag/js/"
  },
  {
    name: "v-14a9a50c",
    path: "/tag/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-14a9a50c").then(next)
    },
    meta: {"pid":"tags","id":"html"}
  },
  {
    path: "/tag/html/index.html",
    redirect: "/tag/html/"
  },
  {
    name: "v-97019ce8",
    path: "/tag/工具/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-97019ce8").then(next)
    },
    meta: {"pid":"tags","id":"工具"}
  },
  {
    path: "/tag/工具/index.html",
    redirect: "/tag/工具/"
  },
  {
    name: "v-c69b8932",
    path: "/tag/jquery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c69b8932").then(next)
    },
    meta: {"pid":"tags","id":"jquery"}
  },
  {
    path: "/tag/jquery/index.html",
    redirect: "/tag/jquery/"
  },
  {
    name: "v-00b7e87f",
    path: "/tag/前端性能/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-00b7e87f").then(next)
    },
    meta: {"pid":"tags","id":"前端性能"}
  },
  {
    path: "/tag/前端性能/index.html",
    redirect: "/tag/前端性能/"
  },
  {
    name: "v-cd93ecc0",
    path: "/tag/杂谈/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-cd93ecc0").then(next)
    },
    meta: {"pid":"tags","id":"杂谈"}
  },
  {
    path: "/tag/杂谈/index.html",
    redirect: "/tag/杂谈/"
  },
  {
    name: "v-12c16540",
    path: "/tag/vue源码/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-12c16540").then(next)
    },
    meta: {"pid":"tags","id":"vue源码"}
  },
  {
    path: "/tag/vue源码/index.html",
    redirect: "/tag/vue源码/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-5888b7d5",
    path: "/categories/Python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5888b7d5").then(next)
    },
    meta: {"pid":"categories","id":"Python"}
  },
  {
    path: "/categories/Python/index.html",
    redirect: "/categories/Python/"
  },
  {
    name: "v-7f0f18bb",
    path: "/categories/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0f18bb").then(next)
    },
    meta: {"pid":"categories","id":"git"}
  },
  {
    path: "/categories/git/index.html",
    redirect: "/categories/git/"
  },
  {
    name: "v-7f1260c2",
    path: "/categories/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f1260c2").then(next)
    },
    meta: {"pid":"categories","id":"npm"}
  },
  {
    path: "/categories/npm/index.html",
    redirect: "/categories/npm/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-35a5b228",
    path: "/categories/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-35a5b228").then(next)
    },
    meta: {"pid":"categories","id":"js"}
  },
  {
    path: "/categories/js/index.html",
    redirect: "/categories/js/"
  },
  {
    name: "v-62e70386",
    path: "/categories/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-62e70386").then(next)
    },
    meta: {"pid":"categories","id":"html"}
  },
  {
    path: "/categories/html/index.html",
    redirect: "/categories/html/"
  },
  {
    name: "v-7f958298",
    path: "/categories/工具/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f958298").then(next)
    },
    meta: {"pid":"categories","id":"工具"}
  },
  {
    path: "/categories/工具/index.html",
    redirect: "/categories/工具/"
  },
  {
    name: "v-ab5e831a",
    path: "/categories/jquery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-ab5e831a").then(next)
    },
    meta: {"pid":"categories","id":"jquery"}
  },
  {
    path: "/categories/jquery/index.html",
    redirect: "/categories/jquery/"
  },
  {
    name: "v-018ee2ea",
    path: "/categories/前端性能/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-018ee2ea").then(next)
    },
    meta: {"pid":"categories","id":"前端性能"}
  },
  {
    path: "/categories/前端性能/index.html",
    redirect: "/categories/前端性能/"
  },
  {
    name: "v-644c5aac",
    path: "/categories/杂谈/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-644c5aac").then(next)
    },
    meta: {"pid":"categories","id":"杂谈"}
  },
  {
    path: "/categories/杂谈/index.html",
    redirect: "/categories/杂谈/"
  },
  {
    name: "v-70a0d0d4",
    path: "/categories/vue源码/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-70a0d0d4").then(next)
    },
    meta: {"pid":"categories","id":"vue源码"}
  },
  {
    path: "/categories/vue源码/index.html",
    redirect: "/categories/vue源码/"
  },
  {
    name: "v-7f161587",
    path: "/categories/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f161587").then(next)
    },
    meta: {"pid":"categories","id":"vue"}
  },
  {
    path: "/categories/vue/index.html",
    redirect: "/categories/vue/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]